import streamlit as st
import pandasai as pai

from pandasai_litellm.litellm import LiteLLM


# ------------------------------------------------
# Page Configuration
# ------------------------------------------------

st.set_page_config(
    page_title="AI Sales Analyzer",
    page_icon="📊",
    layout="wide"
)


# ------------------------------------------------
# Title
# ------------------------------------------------

st.title("📊 AI Sales Data Analyzer")

st.write(
    "Ask questions about the sales data using natural language "
    "and let Gemini + PandasAI calculate the answer."
)


# ------------------------------------------------
# Gemini API Key
# ------------------------------------------------

api_key = st.sidebar.text_input(
    "Enter Gemini API Key",
    type="password"
)


# ------------------------------------------------
# Load CSV
# ------------------------------------------------

@st.cache_data
def load_data():
    return pd.read_csv("sales_data.csv")


import pandas as pd

data = load_data()


# ------------------------------------------------
# Display Dataset
# ------------------------------------------------

st.subheader("📁 Sales Dataset")

st.dataframe(
    data,
    use_container_width=True
)


# ------------------------------------------------
# Configure PandasAI
# ------------------------------------------------

if api_key:

    llm = LiteLLM(
        model="gemini/gemini-3.5-flash",
        api_key=api_key
    )

    pai.config.set({
        "llm": llm
    })


    # --------------------------------------------
    # Predefined Questions
    # --------------------------------------------

    st.subheader("🤖 Ask AI")

    questions = {
        "Total Revenue":
            "Calculate the total revenue from all sales. Revenue is Quantity multiplied by UnitPrice.",

        "Average Order Value":
            "Calculate the average order value for all orders. Use Quantity multiplied by UnitPrice for each order.",

        "Highest Revenue Product":
            "Calculate the total revenue for each product and identify the product with the highest total revenue.",

        "City-wise Revenue":
            "Calculate the total revenue generated by each city and tell me which city has the highest revenue.",

        "Best Salesperson":
            "Calculate the total revenue generated by each salesperson. Identify the highest-performing salesperson and show their total revenue."
    }


    selected_question = st.selectbox(
        "Select a question",
        list(questions.keys())
    )


    if st.button("🔍 Analyze"):

        question = questions[selected_question]

        with st.spinner("Gemini is analyzing the data..."):

            try:

                # Convert normal Pandas DataFrame
                # into PandasAI DataFrame

                df = pai.DataFrame(data)

                result = df.chat(question)

                st.success("Analysis completed!")

                st.subheader("🤖 AI Result")

                st.write(result)

            except Exception as e:

                st.error(f"Error: {e}")


    # --------------------------------------------
    # Custom Question
    # --------------------------------------------

    st.subheader("💬 Ask Your Own Question")

    custom_question = st.text_input(
        "Example: Which city sold the most laptops?"
    )


    if st.button("🚀 Ask AI"):

        if custom_question:

            with st.spinner("Gemini is thinking..."):

                try:

                    df = pai.DataFrame(data)

                    result = df.chat(custom_question)

                    st.subheader("🤖 AI Answer")

                    st.write(result)

                except Exception as e:

                    st.error(f"Error: {e}")

        else:

            st.warning("Please enter a question.")


else:

    st.info(
        "👈 Enter your Gemini API key in the sidebar to start AI analysis."
    )